### ISSUE TITLE
Passwords aren't salted and hashed

### ISSUE THREAD

**Issue by SomeoneElse37** [lenscas/rp_tracker#14]
Looking at /application/models/Users_model.php, it appears that users' passwords are stored in the database after being encrypted with some kind of reversible cipher. This is **bad practice**, although, granted, not as bad as just storing the passwords in plaintext. If somebody hacks your database and manages to obtain the encrypted passwords and the encryption key, *bam* everyone's accounts are compromised (and, quite possibly, a bunch of their other accounts for things online because password reuse is a thing that people do even though it's a security vulnerability).

The gold standard for storing passwords (AFAIK) is to first salt them with a random number also stored in the database and associated with each user, and then run them through a cryptographic (and irreversible) hash function before storing the result. When users login, they can be authenticated by salting and hashing the password they type in the same way, and comparing the result to the hash stored in the database.

Using a hash function instead of an encryption algorithm ensured that there's no way that an attacker could (in a reasonable amount of time) guess the encryption key and crack everyone's passwords at once. Salting the passwords before hashing them ensures that even if two users have the same password, they won't have the same hash- so cracking any particular hash won't give an attacker any info about other users' passwords.

**Comment by RealKC** [comment]
This( http://php.net/manual/en/faq.passwords.php) documentation seems to be pretty good.

**Comment by lenscas** [comment]
I was already aware of all that and it is on the list of things to do. There are currently however more important things to get fixed (XSS for example). 

I believe that in one of the school projects I have there is a good way to store the passwords, however that was written for another framework and admittedly not written by me but reusing it should be doable. 

edit: found it
https://github.com/lenscas/Mini-Geo-master/blob/master/application/model/login_model.php

However, I will need to rewrite all the database queries into those that CI uses among a few other things. The massive check also needs to be changed to use the input validation from CI but that was also already the case with the current version.

**Comment by RealKC** [comment]
Lens, nothing is more important than security

**Comment by lenscas** [comment]
That is why XSS is more important right now. Currently even if the database gets comprised the encryption key is still needed which although not ideal is better then nothing. XSS on the other hand has in this build not been stopped and as such can do a lot more damage. Same with Request forgery. Both are being worked on after that I will look into a better way to store the passwords.

**Comment by lenscas** [comment]
Fixed in 7235155 . It now uses the php functions password_hash and password_verify.
